language: java
jdk:
- oraclejdk8
env:
  global:
  - ONOS_ROOT=$TRAVIS_BUILD_DIR
  - KARAF_TAR=/tmp/apache-karaf-$KARAF_VERSION.tar.gz
before_script:
- source $ONOS_ROOT/tools/dev/bash_profile
after_success:
- source $ONOS_ROOT/tools/dev/bash_profile
- onos-package
notifications:
  email: st+travis-onos-test@st-g.de
deploy:
  provider: releases
  api_key:
    secure: BIu61RXW8ltgd7UJbHgVODh4jZwyA/HqSObsLMEqWKfh+TMgE2Zu0spA9c2EKxtv2fOujaJtVkP3ZmgwR5UeJVeDilAPn8OzAAHxRgSO/uX0vHIEUb6yU6zItE/SuZ1KSYoBIZ6qRbowxlVYHCNz2X6SjalwWoeb+i1/PJ7MWB4zHNGfCeiaRgeSGRe0jA/O3EzijeSjx9dyXa/c2CN5B0luFBTXs9cOH+VkaKN6N1IUBHNKWVJPfgPXgTSlu7cTS1sDXRdXicl77snPc7og29sjNww2d7aK1i6LfuTWVPtw5gUPYHzVoSlDxlHaYCCROn/fPto2j3/XAvX08mzrEZuyk72JvMpbwE/NPRjMzrzal0xjd7Byvxyktn6ztp76sDV0HhLrZubCE8P19sMSx3NDuFD0y5FMGUeCLdnNC4JfTa2k3yl4zK78KlqAQtlRiidHYkKh0qqcj3NRxyLLJtU3UipxziKtv0mH8jz4y0wMy3Is5uKTtKqU36+FQrByt5udHj7aqKVVX+uG8MCnqQ/6NAWvhp+wrpsHZJH4lA/kONKIQUR20SgBHkyE4fd0EPHc9Jt6Bb3by5SxF+G3dIsDT1fDH8E+NwrxB1cup4fKv8ABBdp4dI4LNr95CaSQMOWnvCqNn8eSXO+q8xqiy0LW0SzOGKwNeYXxCphoEyg=
  file:
#  - /tmp/onos-1.4.0.travis.tar.gz
  - /tmp/onos-1.4.0.travis.zip
  on:
    repo: StephenKing/onos
    branch: travis-ci
    tags: true
after_deploy:
- echo 'deployed!'
